# Update this with your actual secret key in production
# For production, use a strong secret key generated by a tool like:
# python -c "import secrets; print(secrets.token_urlsafe(32))"
SECRET_KEY = "your-secret-key-here-change-in-production"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30